export const actionTypes = {
    TOGGLE_THEME: "TOGGLE_THEME",
    HYDRATE: "HYDRATE",
    RESTORE: "RESTORE",
    UPDATE_LEARNING_LIST: "UPDATE_LEARNING_LIST",
    ADD_TO_LEARNING_LIST: "ADD_TO_LEARNING_LIST",
    REGISTER_USER: "REGISTER_USER",
    SWITCH_MODE: "SWITCH_MODE"
}